---
# defaults file for provision_ansible_pull_update
# schedule is fed directly to cron
schedule: '*/20 * * * *'

# User to run ansible-pull as from cron
cron_user: ec2-user

# Group to run ansible-pull as from cron on SUSE
suse_group: users

# File that ansible will use for logs
logfile: /var/log/ansible-pull.log

# Directory to where repository will be cloned
workdir: /var/lib/ansible/local

# Repository to check out -- YOU MUST CHANGE THIS
# repo must contain a local.yml file at top level
#repo_url: https://github.com/jschulthess/ansible-pull-update.git
repo_url: https://github.com/jarmandomtz/ansible-book-repo

# host command
host_cmd: '-i localhost'

# Specific branch
branch_cmd: '-C main'

# Ansible Starter file
ansible_file: nodeserver.yml
